return PlaceObj('ModDef', {
	'title', "Ukrainian Sponsor",
	'description', "This mod is still a work in progress. Please hop in discord to help test or provide feedback. :)   https://discord.gg/kTgYq9UjWx",
	'image', "Images/thumbnail.png",
	'last_changes', "https://github.com/Surviving-Mars-Mods/Ukraine-Sponsor",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"src/*",
		"Info/2do.txt",
		"*.iml",
		".idea/*",
		"*.png",
	},
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "FIZZLE1",
			'title', "Fizzle Fuze's Library",
			'version_major', 1,
			'version_minor', 5,
		}),
	},
	'id', "UKRAINE2022",
	'steam_id', "",
	'pops_desktop_uuid', "5f7e3bd5-efca-4aba-b5b0-ddb4255296ee",
	'pops_any_uuid', "93e43deb-0ffa-49ff-9645-104057165d80",
	'author', "Fizzle Fuze",
	'version_major', 1,
	'version_minor', 1,
	'version', 69,
	'lua_revision', 1009413,
	'saved_with_revision', 1010838,
	'saved', 1646320611,
})